services:
  - type: web
    name: url-shortener
    env: node
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/UrlShortner-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 21
